# Generated by Django 3.2.8 on 2022-03-21 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', default='', null=True)),
                ('code', models.CharField(db_column='code', max_length=100)),
                ('price', models.FloatField(db_column='price', null=True)),
                ('rating', models.IntegerField(db_column='rating')),
                ('review_count', models.IntegerField(db_column='review_count')),
                ('img', models.TextField(blank=True, db_column='img', default='', null=True)),
                ('cat', models.CharField(db_column='cat', max_length=100)),
                ('create_at', models.DateTimeField(db_column='create_at', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'MASTER_PRODUCTS',
            },
        ),
    ]
